#!/bin/bash

pushd ~/slork/users/ant/etude2
# pushd ~/college/spring26/cs170/slork/etude2

# kb_device=$(chuck --probe 2>&1 | awk '/keyboard/{kb=1} kb && /Apple Internal Keyboard/{gsub(/[][]/, "", $2); print $2; exit}')

open score.jpg



popd
